name: Update Gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install CLI
        run: |
          npm install -g douban-status-tracker
      - name: Run Script
        run: |
          douban-status-tracker
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          DOUBAN_ID: ${{ secrets.DOUBAN_ID }}
          DOUBAN_COOKIE: ${{ secrets.DOUBAN_COOKIE }}
